# Generated by Django 4.0.1 on 2022-01-15 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=50)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=10)),
                ('food_type', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=40)),
                ('cusstm', models.ManyToManyField(to='hello.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.CharField(max_length=10)),
                ('discount_on', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('headshot', models.ImageField(upload_to='hello/media')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('contact_no', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=40)),
                ('jobrole', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('cusst', models.ManyToManyField(to='hello.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Serves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.customer')),
                ('staffs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=10)),
                ('transaction_type', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.customer')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.menu')),
            ],
        ),
    ]
