# Generated by Django 4.0.1 on 2022-01-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='cusstm',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='cus',
            new_name='ordered_by',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='cust',
            new_name='customer_bill',
        ),
        migrations.RenameField(
            model_name='serves',
            old_name='custo',
            new_name='served_to',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='headshot',
        ),
    ]
