# Generated by Django 4.0.1 on 2022-01-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_rename_cusstm_menu_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='food_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='food_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='offers',
            name='discount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offers',
            name='discount_on',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Foodoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('foodtype', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
                ('order', models.ManyToManyField(to='hello.Customer')),
            ],
        ),
    ]
