# Generated by Django 4.0.1 on 2022-02-07 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_customer_pwd_customer_uname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='uname',
            new_name='usrname',
        ),
    ]
