# Generated by Django 4.0.1 on 2022-02-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_rename_uname_customer_usrname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='usrname',
            field=models.EmailField(max_length=254),
        ),
    ]
