# Generated by Django 4.0.1 on 2022-02-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_alter_customer_usrname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact_no',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='website',
        ),
    ]
