# Generated by Django 4.0.1 on 2022-02-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_alter_customer_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='foodname',
            field=models.CharField(default='', max_length=500),
        ),
    ]
