# Generated by Django 4.0.1 on 2022-02-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_menu_food_id_orders_foodid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='food',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='ordered_by',
        ),
    ]
