# Generated by Django 4.0.1 on 2022-02-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_remove_orders_food_remove_orders_ordered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodoffer',
            name='order',
        ),
        migrations.AddField(
            model_name='offers',
            name='order',
            field=models.ManyToManyField(to='hello.Customer'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='discount_on',
            field=models.CharField(max_length=500),
        ),
    ]
