# Generated by Django 4.0.1 on 2022-02-08 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_remove_foodoffer_order_offers_order_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foodoffer',
        ),
    ]
