# Generated by Django 4.0.1 on 2022-02-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_delete_foodoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='discount_on',
            new_name='discounton',
        ),
    ]
