# Generated by Django 4.0.1 on 2022-02-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_rename_discount_on_offers_discounton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='food_name',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_type',
            new_name='transactiontype',
        ),
    ]
