# Generated by Django 4.0.1 on 2022-02-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_rename_amount_payment_food_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer_bill',
        ),
    ]
