# Generated by Django 4.0.1 on 2022-03-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0016_remove_payment_customer_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cuid',
            field=models.CharField(default='', max_length=500),
        ),
    ]
