# Generated by Django 4.0.1 on 2022-03-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0017_orders_cuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='food_id',
        ),
    ]
