# Generated by Django 4.0.1 on 2022-03-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0018_remove_menu_food_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='foodid',
        ),
    ]
