# Generated by Django 4.0.1 on 2022-03-17 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0019_remove_orders_foodid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.customer'),
        ),
    ]
