# Generated by Django 4.0.1 on 2022-03-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0021_remove_orders_cuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cuid',
            field=models.CharField(default='', max_length=500),
        ),
    ]
