# Generated by Django 4.0.1 on 2022-03-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0024_remove_offers_cuid_payment_cuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ManyToManyField(to='hello.Customer'),
        ),
    ]
