# Generated by Django 4.0.1 on 2022-03-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0025_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='food_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
    ]
