# Generated by Django 4.0.1 on 2022-03-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0026_remove_payment_food_name_remove_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='food_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
