# Generated by Django 4.0.1 on 2022-03-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0028_alter_orders_cuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cuid',
            field=models.CharField(default='', max_length=500),
        ),
    ]
